### ISSUE TITLE
atom_box_outline when clicked

### ISSUE THREAD

**Issue by 60-hz** [sebshader/pdnext#10]
Would it be possible to separate "atom_box_outline" and "atom_box_outline_highlight" color (when user click on the atom box, the "atom_box_outline" width is simply wider) ?

**Comment by sebshader** [comment]
@60-hz I transferred the issue as it is for pd-next (atom_box_outline_highlight isn't available).
I'll think about this and have a look at the code

**Comment by sebshader** [comment]
@60-hz ok I added this feature to pure-data/#196 and it will be in the next release as atom_box_focus_outline
