### ISSUE TITLE
pdwindow text highlight

### ISSUE THREAD

**Issue by 60-hz** [sebshader/pdnext#11]
If I am not mistaken, the pdwindow_post_text highlight is still hardcoded and not available in the color-plugin (kind of light gray by default).

Small detail, "txt_highlight_front" is not described in the plugin comments.

**Comment by sebshader** [comment]
@60-hz when would a user need to highlight text in the pd window? for copying error messages?

**Comment by 60-hz** [comment]
During a workshop, when I want to focus the students on a special text log on the console screen.

**Comment by sebshader** [comment]
@60-hz I added it to pure-data/pure-data#196 as ```pdwindow_hl_text```
