### ISSUE TITLE
MIDI API selection in Media menu is missing from pdnext

### ISSUE THREAD

**Issue by jamshark70** [sebshader/pdnext#20]
I found to my surprise this afternoon, in a class, that I couldn't open a MIDI port. (New machine, I had only installed pdnext, not pure-data.)

I could have sworn that the Media menu in pd vanilla has a switch for the MIDI API, but I couldn't find it in pdnext.

So I just downloaded and built pd vanilla (which I don't plan to use anyway, but...). ... And there's "OSS MIDI" and "ALSA MIDI" right there in the Media menu.

AFAICS, then, the only way to configure MIDI in pdnext is to install pd vanilla, configure it there, and then pdnext will pick it up from the .pdsettings file.

EDIT: I spoke too soon... pdnext says "opened 0 MIDI input device(s) and 0 MIDI output device(s)" and there seems to be no way to fix it. That's unfortunate. The color themes were saving my eyes but I sometimes need to use MIDI in class.

**Comment by sebshader** [comment]
@jamshark70 I have only ever been able to compile pd without oss midi support personally. (that includes pd vanilla, not just pd-next).. What flags did you build vanilla with?
you can try compiling with my flags (after installing the alsa & jack header/dev packages): 
```./configure --enable-jack CFLAGS=""```
for me that doesn't seem to supply any selection of midi api in the media menu though, only audio apis. It just opens alsa midi window if I select "midi preferences". However alsa midi usually works perfectly well.
sometimes the preferences have gotten corrupted before in which case it gets fixed when I start pd with the -alsamidi flag (but I have never seen any option for OSS MIDI..)

**Comment by jamshark70** [comment]
> edit: from what you said it seems like you ONLY had OSS running

No, I've never used OSS MIDI and I never will. Zero interest in that. I only said that pd vanilla includes an OSS MIDI and ALSA MIDI menu option -- I mentioned OSS first because it appears higher in the menu.

ALSA MIDI. I need interoperability with other ALSA MIDI apps (or connectivity to a2jmidid).

`-alsamidi` does not help.

```
    audio APIs:           PortAudio JACK ALSA OSS 
    midi APIs:            ALSA OSS 
```

I can only ever get `opened 0 MIDI input device(s) and 0 MIDI output device(s).`.

**Comment by jamshark70** [comment]
Pd-vanilla:

![pd-vanilla-media](https://user-images.githubusercontent.com/318301/203072840-3e3030cd-9ad5-4024-a82a-427964c4451b.png)

![pd-vanilla-midi](https://user-images.githubusercontent.com/318301/203072866-f90fc5f1-9147-4f3e-92b0-d64e06b401b1.png)

Pdnext:

![pdnext-media](https://user-images.githubusercontent.com/318301/203072913-3f54acf6-f1ab-4012-ad49-7a53f4fcea3c.png)

![pdnext-midi](https://user-images.githubusercontent.com/318301/203072935-c9267fce-81f9-44fd-8487-c1a1fd232287.png)

I'm quite baffled.

**Comment by sebshader** [comment]
@jamshark70 yes it seems like somehow pdnext isn't getting compiled with alsa.. it isn't in the audio device list either..

because that is the screen I get when I select "OSS" for midi, the top is for alsa

**Comment by jamshark70** [comment]
OK then... so how do I switch the configure flags? I do `./configure --enable-jack CFLAGS=""` and nothing gets rebuilt.

Have to make clean or something? Not well documented.

**Comment by sebshader** [comment]
sometimes doing ```autoreconf``` can work before reconfiguring, and ```sudo make clean``` or even ```sudo make distclean``` after reconfiguring but before doing ```make```

**Comment by sebshader** [comment]
ok I'll convert this to a discussion because you aren't the 1st person to have issues with needing to ```make clean``` to fix build configuration for midi on linux
