### ISSUE TITLE
"Pd documents directory" isn't respected in pdnext

### ISSUE THREAD

**Issue by jamshark70** [sebshader/pdnext#22]
Apparently, Pd 0.52.1 packaged for debian stores the "Pd documents directory" location not in .pdsettings, but rather in `~/.config/Pd/org.puredata.pd.pd-gui/docspath.conf` along with two other files, dekenpath.conf and recentfiles.conf.

pdnext isn't looking at these configuration files. (Actually I am quite surprised to find these three files -- I'm pretty sure in the past that these options were set in .pdsettings. Oh well.)

Nor does it provide "Pd documents directory" in the Path preferences panel.

So, every time I start pdnext (and every time it gets confused about a save/load location, which is like every time you breathe funny [pd vanilla problem, not specifically pdnext]), it reverts to ~/Documents.

I don't keep Pd stuff at this level. So I am repeatedly navigating through multiple levels of subfolders to get to the actual files.

Could this very useful option perhaps be ported forward into pdnext?

**Comment by sebshader** [comment]
@jamshark70 if you start pd with ```pd-gui``` instead of ```pd``` the docsdir option should work.
In the next release of pdnext I hope to include the .desktop file installer and icons, in which case pdnext will open like pd vanilla does.
when the 'documents' option comes up in vanilla you're starting it via some desktop menu/shortcut, right?

**Comment by jamshark70** [comment]
Oh I see... indeed, that fixes it, I changed my pdnext.desktop file to pd-gui and now it's fine.

I love scarcely- (or un-)documented folklore :grin:

**Comment by sebshader** [comment]
I actually had to go through the code to figure it out myself hehe
