### ISSUE TITLE
Pull multichannel from main repository

### ISSUE THREAD

**Issue by jamshark70** [sebshader/pdnext#23]
I only just became aware of new multichannel DSP features in PD main :open_mouth: most commits within the last month. Should be pretty much backend stuff (I guess?), so not too hard to merge in? ("Should" be lol)

**Comment by sebshader** [comment]
I usually merge changes when a release happens but maybe I can do it a bit early

**Comment by sebshader** [comment]
closed @ 98c46d5f596fe026b2db2c3d4ceef25c1e89b050

**Comment by jamshark70** [comment]
Oh OK, I was just going to say, if it's unreleased then maybe better to wait :laughing: -- but already done. I'd only recently looked at mc in max, then spotted mention of it for Pd and was curious.
