### ISSUE TITLE
Any chance for a 0.53-1 windows release?

### ISSUE THREAD

**Issue by 60-hz** [sebshader/pdnext#24]
Hi,
I need to use recent Gem lib for a class and I see that I need pd-0.53 for that...
any chance for a compiled Windows version of pdnext 0.53-1?

**Comment by sebshader** [comment]
Not yet sorry, my MacBook broke and I don't think my new computer has enough memory to run a VM
Might be able to do it thru GitHub actions or cross-compiling w/ Mingw. I'll leave this open and try to investigate
