### ISSUE TITLE
App cannot open under MacOS Sonoma

### ISSUE THREAD

**Issue by 60-hz** [sebshader/pdnext#25]
New version of MacOS Sonoma 14.0 cannot open the app.
Gatekeeper is desactivated.

Tried:
 "sudo xattr -cr /path/to/app"

 "sudo xattr -r -d com.apple.quarantine /path/to/app"

Still same issue...

<img width="303" alt="Capture d’écran 2023-10-17 à 13 30 51" src="https://github.com/sebshader/pdnext/assets/5449719/15c90489-bf6b-46b9-9e34-abb567896b32">

**Comment by sebshader** [comment]
I'm assuming you tried right click-> open.
Does vanilla open?

**Comment by 60-hz** [comment]
>I'm assuming you tried right click-> open.

Yes

>Does vanilla open?

Vanilla 0.54 from miller opens yes, from a .dmg

**Comment by sebshader** [comment]
@60-hz it probably won't help, but could you try the artifact from here? https://github.com/sebshader/pdnext/actions/runs/6554512134

**Comment by 60-hz** [comment]
It works perfectly...  and also fix [this vanilla puredata issue with MacOS Sonoma](https://github.com/pure-data/pure-data/issues/2105). Did you use another tcl version?

**Comment by sebshader** [comment]
Hmm strange. Yes a user had compiled wish for me I think it's 8.6.13. If you turn log level up it should say in the console I think.

**Comment by 60-hz** [comment]
Correct.
